# Site settings
title: Bingozx Blog
SEOTitle: Bingozx的技术博客 | Bingozx Tech Blog
header-img: img/home-bg.jpg
email: your-email@domain.com
description: "编程改变世界 | 这里是 @Bingozx 的个人技术博客，与你一起探索编程的乐趣"
keyword: "Bingozx, 博客, 个人网站, 互联网, Web, 前端, 后端, 全栈"
url: "https://blog-9ch.pages.dev"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username: your-weibo-username
#zhihu_username:  your-zhihu-username
github_username: bingozx
#twitter_username: your-twitter-username
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: bingozx

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-XXXXXXXX-X'
# ga_domain: auto

# Sidebar settings
sidebar: true
sidebar-about-description: "写代码改变世界<br>Code to change the world"
sidebar-avatar: https://github.com/bingozx.png # use absolute URL

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "GitHub", href: "https://github.com/bingozx" },
    { title: "乱序（Midare）", href: "http://mida.re/" },
    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    { title: "Kun Qian", href: "http://kunq.me" },
    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    { title: "SmdCn", href: "http://blog.smdcn.net" },
    { title: "JiyinYiyong", href: "http://tiye.me/" },
    { title: "DHong Say", href: "http://dhong.co" },
    { title: "尹峰以为", href: "http://ingf.github.io/" },
  ]
